version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    allowed_updates:
      - match:
          update_type: 'security'
      - match:
          dependency_name: 'codemirror'
          dependency_type: 'direct'
    commit_message:
      prefix: 'chore'
      prefix_development: 'chore'
      include_scope: true
