name: Deploy on Firebase

on:
  push:
    tags:
      - '*'

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - name: determine version
      id: determine_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - run: npm install
    - run: npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: 'deploy -m "release: ${{ steps.determine_version.outputs.VERSION }}"'
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
